name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: your-github-username
          template: classic
          base: header, activity, community, repositories, metadata
